# Generated by Django 6.0.4 on 2026-06-09 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_pay"),
    ]

    operations = [
        migrations.AddField(
            model_name="pay",
            name="product",
            field=models.CharField(
                blank=True,
                help_text="Укажите продукт",
                max_length=50,
                null=True,
                verbose_name="Продукт",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.PositiveIntegerField(
                help_text="Укажите сумму оплаты", verbose_name="Сумма оплаты"
            ),
        ),
    ]
