# Generated by Django 6.0.4 on 2026-06-03 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_course_owner_lesson_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscribe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_subscribe",
                    models.BooleanField(default=False, verbose_name="признак подписки"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="Укажите название курса",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscribers",
                        to="materials.course",
                        verbose_name="курс",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Укажите название курса",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="курс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подписка",
                "verbose_name_plural": "Подписка",
            },
        ),
    ]
